channels:
  - ome
  - conda-forge
  - joshmoore
  - defaults
dependencies:
  - python == 3.9.0
  - ipython
  - wheel
  - requests
  - h5py
  - s3fs
  - scikit-image
  - scipy
  - xarray
  - zarr >= 2.7.0
  - go-mc
  - pip
  - pip:
      - PyQT5==5.13.1
      - ome-zarr
      - awscli
      - pytest-benchmark
      - boto3
