- hosts: all
  vars:
    # Should already be set for terraform
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID')}}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY')}}"

  tasks:

    - apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'docker-ce', 'python3', 'python3-pip', 'awscli']

    - pip: name={{ item }} executable=pip3
      loop: ['docker', 'docker-compose']

    - ansible.builtin.git:
        repo: 'https://github.com/ome/ngff-latency-benchmark'
        dest: 'ngff-latency-benchmark'

    - ansible.builtin.command:
        argv: ["aws", "configure", "set", "aws_access_key_id", "{{ access_key }}"]
      tags: aws

    - ansible.builtin.command:
        argv: ["aws", "configure", "set", "aws_secret_access_key", "{{ secret_key }}"]
      tags: aws

- hosts: servers
  tasks:

    - docker_compose:
        project_src: "ngff-latency-benchmark"
        state: "present"
        services:
          - "nginx"

- hosts: clients
  tasks:

    - ansible.builtin.command:
        chdir: ngff-latency-benchmark
        argv: ["docker-compose", "build", "benchmark"]
