---
name: Build

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: |
          rm .env
          mv .env-gha .env
      - name: Build
        run: |
          docker-compose pull && docker-compose build
      - name: Generate
        run: ./generate.sh
      - name: Start Upload and Run benchmark
        run: ./test.sh
      - name: Check logs
        run: docker-compose logs
        if: ${{ failure() }}
